### ISSUE TITLE
how to support chinese UTF-8 ?

### ISSUE THREAD

**Issue by insomnia417** [accetto/headless-drawing-g3#5]
Browser display is full of garbled code with CN

**Comment by accetto** [comment]
Hello,

you will need to install the chinese locale resources and set the required environment variables. You have to search on Internet how to do it, because I'm not able to test such an environment correctly. The image is based on `ubuntu` and you can use `sudo`, so you should not have any problems, I think.

You can find the following links useful:

- [Configure Locales in Ubuntu](https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu)
- [Ubuntu - Locale](https://help.ubuntu.com/community/Locale)

Regards,
accetto

**Comment by accetto** [comment]
Closing because of no further actions from the requester.
